### ISSUE TITLE
Provide support for iOS

### ISSUE THREAD

**Issue by Sohit-Sharma** [chaudharydeepanshu/pdf_manipulator#3]
Hi,

Firstly i would like to thank you for this library. It contains the lots of features. As this lib is for flutter framework, so you have to provide at least basic platforms support i.e Android/iOS. It's working fine in android but provide the iOS as well.

Thanks

**Comment by chaudharydeepanshu** [comment]
Hi,

Thank you for your understanding and feedback. Unfortunately, due to the lack of iOS devices in my vicinity, I am currently unable to develop and test the library for iOS support.

However, I encourage other community members to contribute to the project by adding iOS support if possible. It would help make the library more versatile for all users.

In the meantime, I will try to provide support for iOS once I get my hands on an iOS device.

Also, I'm closing it as it's a duplicate issue #1 .

Thank you.
